# Site Settings
title: COVID-19 no ES
email: edsondelatorre@gmail.com
description: >
  Um repositório da situação da epidemia de COVID-19 no Espírito Santo
baseurl: "/startjekyll"
url: "http://dltrr.github.io"
twitter_username: edsondelatorre
github_username:  dltrr
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
